//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiddleEgyptianDictionary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiddleEgyptianDictionary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DicksonDictionary_ {
            get {
                object obj = ResourceManager.GetObject("DicksonDictionary_", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A1,;i;I, me, my;258.5;
        ///A1,A1,A1,;rmT;man, men, mankind, Egyptians;4;
        ///A1,;=i;I, me, my;258.5;
        ///A113,;smsw  hAyt;Elder of the portal;0;
        ///A12,A1,Z2,;mSa;soldiers, army, infantry, gang (of workmen);0;
        ///A12,P1,;mSa;make an expedition, expedition;0;
        ///A12,D54,Z2,;mSa;expedition;0;
        ///A12,;mSa;expedition;0;
        ///A14,;mt;die, perish, death;8;
        ///A14,X1,;mt;die, perish, death;0;
        ///A15,;xr;fall (in military sense);7.33333;
        ///A15,;xrw;enemy;7.33333;
        ///A15,X1,;sxr;overthrow, throw down, force into place (dislocated bone);0.333333;
        ///A158,D40, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Lexicon {
            get {
                return ResourceManager.GetString("Lexicon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MarkVygusDictionary {
            get {
                object obj = ResourceManager.GetObject("MarkVygusDictionary", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A12,mSa
        ///A15,xr
        ///A17,Xrd
        ///A21,sr
        ///A33,mniw
        ///A38,qiz
        ///A47,iry
        ///A50,Sps
        ///A51,Spsi
        ///J1,x
        ///J11,mAa
        ///J13,gs
        ///J13,im
        ///J15,M
        ///J17,sA
        ///J20,apr
        ///J21,wDa
        ///J27,nD
        ///J28,qd
        ///J30,Xkr
        ///J5,Hp
        ///J8,qn
        ///B3,msi
        ///C10,mAat
        ///C11,HH
        ///C3,DHwty
        ///C4,Xnmw
        ///C6,inpw
        ///C7,stX
        ///C8,mnw
        ///D1,tp
        ///D10,wDAt
        ///D153,R
        ///D19,fnD
        ///D2,Hr
        ///D21,r
        ///D21,rA
        ///D24,spt
        ///D25,spty
        ///D27,mnD
        ///D28,kA
        ///D3,Sny
        ///D34,aHA
        ///D36,a
        ///D4,ir
        ///D45,Dsr
        ///D46,d
        ///D50,Dba
        ///D52,mt
        ///D56,gH
        ///D56,gHs
        ///D56,rd
        ///D56,sbq
        ///D58,b
        ///D59,ab
        ///D60,wab
        ///D61,sAH
        ///D9,rmi
        ///E17,zAb
        ///E22,mAi
        ///E23,l
        ///E2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MdcToGardiner {
            get {
                return ResourceManager.GetString("MdcToGardiner", resourceCulture);
            }
        }
    }
}
